import Head from 'next/head'
import styles from '../styles/Home.module.css'

const startScan = async () => {
  if ('bluetooth' in navigator) {
    try {
      const device = await navigator.bluetooth.requestDevice({
        acceptAllDevices: true,
        optionalServices: ['battery_service'], // Required to access service later.
        // filters: [{ services: ['battery_service'] }],
        // filters: [{ services: ['heart_rate'] }],
      });
      console.log('device:', device);

      // Human-readable name of the device.
      console.log(device.name);

      // Attempts to connect to remote GATT Server.
      console.log('A:', device.gatt?.connected);
      await device.gatt?.connect();
      console.log('B:', device.gatt?.connected);

      // const xx = await device.gatt?.getPrimaryServices('4hhrN3cyNCPf/LO+VNu1ww==');
      // console.log('>>', xx);

      // ...
    } catch (err) {
      console.error('[error]', err);
    }
  } else {
    console.warn('Bluetooth not supported!');
  }  
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Bluetooth Demo</h2>
        <div className={styles.section}>
          <button onClick={() => startScan()}>Start Scan</button>
        </div>
      </main>
    </>
  )
}
