import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

let decoder = new TextDecoder('utf-8');

const startScan = async (setLogs: Function, setElogs: Function) => {
  const printCharacteristic = async (characteristic: BluetoothRemoteGATTCharacteristic) => {
    const uuid = characteristic.uuid;
    const value = await characteristic.readValue();
    const text = decoder.decode(value);
    console.log(text);
    setLogs((v: string[]) => [...v, `${uuid}:${text}`]);
  };

  const printLog = (name: string, value: string | boolean | number | undefined) => {
    if (value === undefined || value === null) value = '';
    const msg = `${name}: ${value.toString()}`;
    console.log(msg);
    setLogs((v: string[]) => [...v, msg]);
  };

  const printError = (value: string, isWarn?: boolean) => {
    if (value === undefined || value === null) value = '';
    const name = isWarn ? 'WARN' : 'ERROR';
    const msg = `${name}: ${value.toString()}`;
    (isWarn ? console.warn : console.error)(msg);
    setElogs((v: string[]) => [...v, msg]);
  };

  if (!('bluetooth' in navigator)) {
    printError('Bluetooth not supported!', true);
    return;
  }
  
  try {
    // const status = await navigator.bluetooth.getAvailability();
    // printLog('status', status);
  
    // window.addEventListener("availabilitychanged", (event) => {});

    const serviceUuid = 0x180A;
    // const serviceUuid = '0000180a-0000-1000-8000-00805f9b34fb';
    printLog('serviceUuid1', serviceUuid);
    printLog('serviceUuid2', `${serviceUuid}`);

    const device = await navigator.bluetooth.requestDevice({
      // acceptAllDevices: true,
      filters: [{
        namePrefix: 'MacBook',
        // manufacturerData: [{
        //   companyIdentifier: 0x00e0,
        //   dataPrefix: new Uint8Array([0x01, 0x02])
        // }],
        // services: ['0000180a-0000-1000-8000-00805f9b34fb'],
      }],
      optionalServices: [serviceUuid],
    });
    printLog('device.name', device.name);
    printLog('device.id', device.id);

    if (!device.gatt) {
      printError('Bluetooth GATT Server not found!');
      return;
    }
    printLog('device.connected', device.gatt.connected);

    const server = await device.gatt.connect();
    if (!server) {
      printError('Bluetooth GATT Server not found! [2]');
      return;
    }

    if (!device.gatt.connected) {
      printError('Unable to connect to Bluetooth GATT Server!');
      return;
    }
    printLog('device.connected', server.connected);

    const service = await server.getPrimaryService(serviceUuid);
    // const service = await server.getPrimaryService('battery_service');

    if (!service) {
      printError(`Bluetooth GATT Service not found: ${serviceUuid}`);
      return;
    }
    printLog('service.available', !!service);

    const chars = await service.getCharacteristics();
    printLog('characteristics.count', chars.length);

    await printCharacteristic(chars[0]);
    await printCharacteristic(chars[1]);

    // const plist = chars.map(async (characteristic) => {
    //   const value = await characteristic.readValue();
    //   const data = value.buffer;
    //   return `uuid,value:${characteristic.uuid},${data}`;
    // });

    // const dlist = await Promise.all(plist);
    // dlist.forEach(data => {
    //   console.log(data);
    //   setLogs((v: string[]) => [...v, data]);
    // });

    // const characteristic = await service.getCharacteristic('battery_level');
    // console.log('characteristic:', characteristic);
    // setLogs((v: string[]) => [...v, `${characteristic}`]);
  } catch (err: any) {
    printError(err.toString());
  }  
};

export default function Home() {
  const [logs, setLogs] = useState<string[]>([]);
  const [elogs, setElogs] = useState<string[]>([]);

  const clearLogs = () => setLogs([]);
  const clearElogs = () => setElogs([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Bluetooth Demo - v8.4</h2>
        <div className={styles.section}>
          <button onClick={() => startScan(setLogs, setElogs)}>Start Scan</button>
        </div>
        <div>
          <h3>Logs:</h3>
          {logs.map((s, i) => (
            <div key={i}>{s}</div>
          ))}
          <button onClick={clearLogs}>Clear</button>
        </div>
        <div>
          <h3>Error:</h3>
          {elogs.map((s, i) => (
            <div key={i}>{s}</div>
          ))}
          <button onClick={clearElogs}>Clear</button>
        </div>
      </main>
    </>
  )
}
